=== Jonas56/miola-biblio/S2/Technologies XML/Ateliers/Atelier 1/cv.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT cv (info-perso, contact, diplome*, conpetence*, experience*, langue+)>
<!ELEMENT info-perso (nom, prenom, sexe, date-naissance)>
<!ELEMENT nom (#PCDATA) >
<!ELEMENT prenom (#PCDATA) >
<!ELEMENT sexe (#PCDATA) >
<!ELEMENT date-naissance (jour, mois, annee)>
<!ELEMENT jour (#PCDATA) >
<!ELEMENT mois (#PCDATA) >
<!ELEMENT annee (#PCDATA) >
<!ELEMENT contact (adresse, phone, mail)  >
<!ELEMENT adresse ANY >
<!ELEMENT phone (#PCDATA) >
<!ELEMENT mail (#PCDATA) >
<!ELEMENT  diplome (designation, date, affiliation, serie, mention)>
<!ELEMENT designation (#PCDATA) >
<!ELEMENT date (#PCDATA) >
<!ELEMENT affiliation (#PCDATA) >
<!ELEMENT serie (#PCDATA) >
<!ELEMENT mention (#PCDATA) >
<!ELEMENT  conpetence (intitule, niveau, description)>
<!ELEMENT intitule (#PCDATA) >
<!ELEMENT niveau (#PCDATA) >
<!ELEMENT description (#PCDATA) >
<!ELEMENT  experience (stage|travail)>
<!ELEMENT  stage (designation, debut, fin, affiliation, mission)>
<!ELEMENT debut (#PCDATA) >
<!ELEMENT fin (#PCDATA) >
<!ELEMENT mission (#PCDATA) >
<!ELEMENT langue (niveau) >
<!ELEMENT  travail (designation, debut, fin, affiliation, mission)>
<!ATTLIST langue designation NMTOKEN #REQUIRED >

=== Jonas56/miola-biblio/S2/Technologies XML/Ateliers/Atelier 1/cv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Document bien formé et valide  -->
<!DOCTYPE cv SYSTEM "cv.dtd"> 
<cv>
    <info-perso>
        <nom>Tesla</nom>
        <prenom>Jonas</prenom>
        <sexe>Masculin</sexe>
        <date-naissance>
            <jour>03</jour>
            <mois>02</mois>
            <annee>2001</annee>
        </date-naissance>
    </info-perso>
    
    <contact>
        <adresse>123 AV. Test</adresse>
        <phone>0606060606</phone>
        <mail>example@mail.com</mail>
    </contact>
    <diplome>
        <designation>BAC</designation>
        <date>2018</date>
        <affiliation>Lycee mohammed 6</affiliation>
        <serie>SC. maths</serie>
        <mention>Bien</mention>
    </diplome>
    <diplome>
        <designation>Licence</designation>
        <date>2021</date>
        <affiliation>Faculté Mohammed 5 Rabat</affiliation>
        <serie>Informatique</serie>
        <mention>Bien</mention>
    </diplome>
    <conpetence>
        <intitule>Dev. Web</intitule>
        <niveau>Intermediare</niveau>
        <description>Developpeur full-stack javascript</description>
    </conpetence>
    <conpetence>
        <intitule>Administrateur système</intitule>
        <niveau>Intermediaire</niveau>
        <description>Linux, Windows</description>
    </conpetence>
    <conpetence>
        <intitule>Project Management</intitule>
        <niveau>Debutant</niveau>
        <description>Agile, Scrum</description>
    </conpetence>
    <experience>
        <travail>
            <designation>Software engineer</designation>
            <debut>2021</debut>
            <fin>Ongoing</fin>
            <affiliation>IBM</affiliation>
            <mission>Build and maintain softwares</mission>
        </travail>
    </experience>
    <experience>
        <stage>
            <designation>Stage d'observation en IoT</designation>
            <debut>2018</debut>
            <fin>2018</fin>
            <affiliation>OCP Group</affiliation>
            <mission>Decouvrir l'application de l'IoT dans le domaine de l'griculture</mission>
        </stage>
    </experience>
    <langue designation="francais">
        <niveau>courant</niveau>
    </langue> 
    <langue designation="anglais">
        <niveau>courant</niveau>
    </langue> 
    <langue designation="arabe">
        <niveau>native/bilingue</niveau>
    </langue> 
</cv>
